log_dir: ./log/model/
data:
  data_file: ./data/SonTay.csv
  split_point_outer: 0.05
  split_point_inner: 0.4
  norm_method: min_max
  cols_x:
    - 2
    - 3
  cols_y:
    - 2
    - 3
  cols_gt:
    - 0
    - 1
  window_size: 30
  target_timestep: 1
model:
  epoch_min: 100
  epoch_num: 4
  epoch_max: 250
  epoch_step: 50
  epochs_out: 400
  in_dim: 2
  out_dim: 2
  patience: 50
  batch_size: 512
  dropout: 0

ssa:
  default_n: 20 # default window size
  sigma_lst: [1,2,3] #default_sigma_lst